# Generated by Django 3.1.4 on 2020-12-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_identifier', models.CharField(max_length=32)),
                ('album', models.CharField(blank=True, max_length=64)),
                ('artist', models.CharField(blank=True, max_length=64)),
                ('artwork_url', models.CharField(blank=True, max_length=256)),
                ('track_number', models.IntegerField(blank=True, null=True)),
                ('total_tracks', models.IntegerField(blank=True, null=True)),
                ('track_title', models.CharField(blank=True, max_length=128)),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='year published')),
                ('add_date', models.DateTimeField(verbose_name='date entry added')),
            ],
        ),
    ]
