# Generated by Django 3.1.4 on 2020-12-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuziekDL', '0002_songentry_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='songentry',
            name='dl_error',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='songentry',
            name='dl_file',
            field=models.FilePathField(blank=True, null=True, path='./songs/'),
        ),
        migrations.AddField(
            model_name='songentry',
            name='dl_status',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Pending'), (2, 'Done'), (-1, 'Error')], default=0),
        ),
    ]
